Added Will Tripp ssh key
stackhpc/terraform-bastion pull request #104
Opened 2024-09-02 10:18 UTC by wtripp180901

2024-09-02 10:56 UTC, dougszumski requested changes
These should now be Yubikeys - I think you will need to get/request one from the office.

2024-09-03 08:51 UTC, Alex-Welsh commented
> These should now be Yubikeys - I think you will need to get/request one from the office.

I agree that they should, but I think it'll be weeks until we can get more keys. As a new starter, it's pretty important that @wtripp180901 has access ASAP for training & R&D tasks, so I think we need to merge this first then update it down the line.

That being said, I've spoken to William in the office and he needs to upload a new key because he doesn't have this one anymore, so he's going to push a new key then we should merge that

2024-09-03 08:53 UTC, Alex-Welsh approved these changes
LGTM but would appreciate a second opinion

2024-09-03 08:55 UTC, assumptionsandg approved these changes

2024-09-03 08:55 UTC, merged